apiVersion: v1
kind: Namespace
metadata:
  name: c2c-metaage-azure-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-metaage-azure-deployment
  namespace: c2c-metaage-azure-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: eslattacr.azurecr.io/azure-demo-push-repo:bd7487a33a13c8ca3b60c336bf30bc9c721d726f

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-metaage-azure-label
  name: c2c-metaage-azure-service
  namespace: c2c-metaage-azure-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---